### ISSUE TITLE
Install error. Could not find pyxpcconnection

### ISSUE THREAD

**Issue by tora16e** [matthewelse/bleep#7]
```
Searching for pyxpcconnection
Reading https://pypi.python.org/simple/pyxpcconnection/
Couldn't find index page for 'pyxpcconnection' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pyxpcconnection
error: Could not find suitable distribution for Requirement.parse('pyxpcconnection')
```

**Comment by matthewelse** [comment]
Hi @trsqxyz thanks for (trying to use) bleep! As it turns out I never got around to putting pyxpcconnection onto PyPi (although it is more or less complete). Could I suggest installing using the instructions here: https://github.com/matthewelse/pyxpcconnection?

There is the secondary problem that the implementation of OS X support is so far incomplete - I've been meaning to come back to it, but I haven't had the time since the most recent updates to pygattosx.

**Comment by tora16e** [comment]
Alright. I hope that all of the package is to support the OS X in the future. Thank you.
